name: Validate

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check README exists
        run: test -f README.md
      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes
          folder-path: .
